### ISSUE TITLE
Fade Out

### ISSUE THREAD

**Issue by luis-cruzt** [rodrigobastosv/loading_overlay#19]
Hi, nice package! Is there a way to let the loading overlay fade out when calling ```context.loaderOverlay.hide();``` ?

Thanks!

**Comment by rodrigobastosv** [comment]
Hi @luis-cruzt , thanks for using this package.

I never thought about this usecase, but it sounds interesting. Let me take a few days so i can see if i figure it out

**Comment by rodrigobastosv** [comment]
Hi @luis-cruzt

I was not successful in my endeavor. I don't think I could because I use streams and I couldn't make them work very well with animation widgets. 

Feel free to try and maybe contribute with the package. I will be very happy if you do. I'll close this issue for know, but feel free to open if you need

Thanks again for using this package!
