### ISSUE TITLE
Selecting between multiple loading overlay.

### ISSUE THREAD

**Issue by wangmir** [rodrigobastosv/loading_overlay#36]
Hi, I'm glad to find this package!

But I have one difficulty when using this.

First of all, I used global loading overlay for global loading view.

But in some cases, i wanna show not global overlay, but loading for some part of view (like, inside button).

So, if u make loading overlay with naming or key, and show loading overlay with that key, then I think we can select between multiple overlay instances.

**Comment by rodrigobastosv** [comment]
Hello @wangmir , thanks so much for using this package.

This is a great proposal. Unfortunately, because the way loading overlay is implemented (using InheritedWidget) is impossible to implement this feature. 

Your idea of using a key to identify the correct Overlay is rather good, and it may work, but for this to work i'll have to make quite a lot of changes on the package.

Please give me a few days to try to implement something and i'll give feedback on this issue.

Again, thanks very much!

**Comment by rodrigobastosv** [comment]
This is a really good issue, but to make it possible a lot of things would change and probably a lot of breaking changes will rise, so i guess is safer to not but this on the package.

**Comment by wangmir** [comment]
@rodrigobastosv ok, I understand.
