### ISSUE TITLE
PopScope is deprecated

### ISSUE THREAD

**Issue by miraquel** [rodrigobastosv/loading_overlay#72]
Hi, I am trying to use the package with minimal setup, but there's an error 

/C:/Users/xxxx/AppData/Local/Pub/Cache/hosted/pub.dev/loader_overlay-3.0.4/lib/src/loader_overlay.dart:196:9: Error: The method 'PopScope' isn't defined for the class '_LoaderOverlayState'.
 - '_LoaderOverlayState' is from 'package:loader_overlay/src/loader_overlay.dart' ('/C:/Users/xxxx/AppData/Local/Pub/Cache/hosted/pub.dev/loader_overlay-3.0.4/lib/src/loader_overlay.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PopScope'.
        PopScope(
        ^^^^^^^^
        
I think the PopScope widget is deprecated.

**Comment by vicenthy** [comment]
Hi, do you need to upgrade your project to version 3.16.x the flutter removes WillPopScope and uses PopScope.

**Comment by JesusHdez960717** [comment]
`WillPopScope` is deprecated since 3.12 [(more info here)](https://stackoverflow.com/questions/77500680/willpopscope-is-deprecated-after-flutter-3-12), so you have to:
1 - Find an old version of this package that use the old `WillPopScope`, or,
2 - Update your Flutter SDK to a version where `PopScope` is the standard. As @vicenthy say, i recommend migrate to 3.16.x, its super stable and word perfect with this package

Extra:
Sadly, the latest version of the packages is tested with the latest versions of the sdk, so it's up to as, the developers, figure it out and finding the version of the packages compatibles with our sdk version. In my specific case, I use [flutter version manager (fvm)](https://fvm.app/) to solve this problems woth flutter sdk, and change and update easily between versions

**Comment by miraquel** [comment]
Noted, thanks for the update

**Comment by JesusHdez960717** [comment]
Hi @miraquel, I know that this issue is already close, but I will like to share my experience with the exact same problem.
The other day I need to use this package in a 'legacy' project with flutter version 3.10.6, and of course, as same as you, I have the `PopScope` error. 
My solution, the number 1 above, I go to the git, find a version that still use the old `WillPopScope`, so basically I use the `3.0.0` version of this package & worker perfect.
